### ISSUE TITLE
Creación de los test

### ISSUE THREAD

**Issue by sixdialla** [Proyecto-EGC-G1/GeneracionEstatica-EGC-G1#18]
Creación de tests en php que permitan comprobar que el plugin realiza sus funciones correctamente.

**Comment by Adelay95** [comment]
Commit asociado f6b4b4070dd06bddeebe1aa154413b705ecd1a0f

**Comment by Adelay95** [comment]
Se ha creado un test de prueba y Travis CI funciona.
Cerrado con el commit aba5a42
