### ISSUE TITLE
Elección del entorno de desarrollo

### ISSUE THREAD

**Issue by SergioTorrijos** [Proyecto-EGC-G1/GeneracionEstatica-EGC-G1#5]
Elección del entorno de desarrollo en el cual importaremos el sistema web para la posterior implementación de los plugings.

**Comment by Adelay95** [comment]
Este issue no cumple con la normativa de las incidencias. Imagine esta situación, usted está trabajando para la empresa Acme Org. S.A. y le piden un documento y usted lo hace como le da la gana, no tardarían en echarle. 

Un saludo.

**Comment by sixdialla** [comment]
Usaremos Wordpress y docker en una máquina virtual Ubuntu.
